from __future__ import annotations

from pathlib import Path

from sqlalchemy import select

from .db.models import Citation, Metric
from .db.session import get_session

HEADER = """# Data Provenance Ledger

This file is auto-generated by `scholarharvester provenance export` and summarizes the most recent harvest for every metric.

| metric_key | value | citation_title | publisher | publication_year | url | interpretation_note |
| --- | --- | --- | --- | --- | --- | --- |
"""


def export_provenance(path: Path) -> None:
    rows: list[str] = []
    with get_session() as session:
        stmt = select(Metric.metric_key, Metric.value_float, Citation.title, Citation.publisher, Citation.publication_year, Citation.url, Citation.interpretation_note).join(Citation)
        for metric_key, value_float, title, publisher, year, url, note in session.execute(stmt):
            rows.append(
                f"| {metric_key} | {value_float if value_float is not None else ''} | {title} | {publisher} | {year} | {url} | {note} |"
            )
    content = HEADER + "\n".join(rows or ["| --pending-- | | | | | | |"])
    path.write_text(content)
